img2img = {
    "template_name": "img2img",
    "init_images": ["brightness_qr.png"],
    "resize_mode": 2,
    "denoising_strength": 0.75,
    "image_cfg_scale": 7.0,
    "prompt": "",
    "styles": [""],
    "seed": -1,
    "subseed": -1,
    "subseed_strength": 0,
    "seed_resize_from_h": -1,
    "seed_resize_from_w": -1,
    "sampler_name": "DPM++ 2M SDE Karras",
    "batch_size": 1,
    "n_iter": 1,
    "steps": 50,
    "cfg_scale": 7,
    "clip_skip": 1,
    "width": 512,
    "height": 512,
    "restore_faces": False,
    "tiling": False,
    "do_not_save_samples": False,
    "do_not_save_grid": False,
    "negative_prompt": "",
    "eta": 0,
    "s_min_uncond": 0,
    "s_churn": 0,
    "s_tmax": 0,
    "s_tmin": 0,
    "s_noise": 1,
    "override_settings": {},
    "override_settings_restore_afterwards": True,
    "script_args": [],
    "sampler_index": "Euler",
    "include_init_images": True,
    "script_name": "",
    "send_images": True,
    "save_images": False,
    "alwayson_scripts": {"controlnet": {"args": []}},
}
